### ISSUE TITLE
Remove onerous requirement for video PRs

### ISSUE THREAD

**Issue by Kintar** [KaijuEngine/kaiju#83]
This project looks very interesting, but honestly this bit of the README makes me nope out of it entirely.

> Every PR will be required to have a video of the development process of that request.

I mean, Oh. My. God. What a nightmare, both for contributors and for the PR reviewers. O.O What do you expect the video format to be like? Are you expecting the entire process of implementing the change to be captured, or just a brief overview? Will there be a requirement for audio commentary? Who's going to edit these things, or are we expected to upload 2-hour videos when implementing a large feature or fixing a big bug?

**Comment by BrentFarris** [comment]
I'm actually considering removing the requirement. For the most part I've just been coding along my happy way by myself, so it was primarily a requirement for myself. However, I have found it hard for me to get things done with that requirement due to having a job and kids. I didn't think anyone would really find my repository here for a while so I didn't think much of it heh.

**Comment by BrentFarris** [comment]
I actually am going to remove it because it literally has been delaying me from submitting commits recently in all honestly

**Comment by kintar** [comment]
Woot! I'll play around with this engine some ASAP, then!
